name: Pack Nuget

on:
  push:
    branches: [ "action/pack" ]
  pull_request:
    branches: [ "action/pack" ]

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Nuget Semi.Avalonia
        run: dotnet pack ./src/Semi.Avalonia -o ./nugets

      - name: Nuget Semi.Avalonia.ColorPicker
        run: dotnet pack ./src/Semi.Avalonia.ColorPicker  -o ./nugets

      - name: Nuget Semi.Avalonia.DataGrid
        run: dotnet pack ./src/Semi.Avalonia.DataGrid  -o ./nugets

      - name: Publish NuGet package
        run: dotnet nuget push "./nugets/*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nugets
          path: ./nugets
